export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const PROGRAM_LOADING = 'PROGRAM_LOADING';
export const INVALID_USER = 'INVALID_USER';
export const GET_PRODUCTS = 'GET_PRODUCTS';